### ISSUE TITLE
Ich bin cool

### ISSUE THREAD

**Issue by 12LuA** [NarmyOnDiscord/xino-rewrite#3]
### Beschreibung

Ich brauch Admin

### Mögliche Commands

!ban @everyone

### Aktuelle Möglichkeit

ka 

### Beispiel

Such dir selber eins aus

### Checklist

- [X] Ich habe nach bereits vorhandenen Featureanfragen gesucht.
- [X] Ich habe alle mir bekannten Informationen weitergegeben.
- [X] Falls ich das Feature woanders gesehen habe, habe ich Bilder angehangen.

**Comment by Lenny59** [comment]
Wir danken Ihnen für den gemeldeten Fliege!
